### ISSUE TITLE
[feature request] 无法读取 IP 数据库时，应设置默认重定向对象

### ISSUE THREAD

**Issue by SerinaNya** [LittleSkinChina/littlesk.in#1]
https://github.com/LittleSkinChina/littlesk.in/blob/eb4511fd671846a5d03828fb4a140d8464a5de1b/api/handler.go#L12-L21

建议在读取 IP 数据库出错时，默认重定向至 <https://littleskin.cn/>，而不**只是**抛出异常并拒绝响应（500）。  
当然，也可以重定向至国内站，这个你说了算。

**Comment by g-plane** [comment]
这个有道理。
